version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine3.15
    container_name: hello-spring-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hello-spring
